name: solutech_sat
description: Cross platform version of Solutech SAT

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --buil  d-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.40+52

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.3+6
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.3+4
  jaguar_orm: ^2.2.5
  jaguar_query: ^2.2.8
  jaguar_query_sqflite: ^2.2.5
  flutter_spinkit: ^3.1.0
  fluttertoast: ^3.0.4
  path_provider: ^0.5.0+1
  date_range_picker: ^1.0.5
  flutter_bluetooth_serial_caravanas: ^0.2.11
  dio: ^2.0.1
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0
  liquid_progress_indicator: ^0.3.1
  flutter_slidable: ^0.4.9
  barcode_scan: ^1.0.0
  validators: ^2.0.0+1
  flutter_offline: ^0.2.4+1
  location: ^2.3.5
  url_launcher: ^5.4.1
  photo_view: ^0.2.1
  flushbar: ^1.2.3
  image_picker: ^0.6.0+2
  image_cropper: ^1.0.1
  flutter_image_compress: ^0.6.3
  flutter_map: ^0.4.0
  expandable: ^2.1.1
  geolocator: ^4.0.3
  permission_handler: ^3.0.0
  auto_size_text: ^1.1.2
  introduction_screen: ^1.0.5+2
  percent_indicator: ^1.0.16
  cached_network_image: ^2.0.0
  google_maps_flutter: ^0.5.20+2
  collection: ^1.14.11
  battery: ^0.3.0+5
  hive: ^1.0.0
  flutter_money_formatter: ^0.8.3
  uuid: ^2.0.2
  great_circle_distance2: ^1.0.1+1
  device_info: ^0.4.0+4
  rflutter_alert: ^1.0.3
  flutter_form_builder: ^3.5.3
  sticky_headers: ^0.1.8
  carousel_slider: ^1.3.1
  flutter_signature_view: ^1.1.1
  timeago: ^2.0.22
  flutter_local_notifications: ^1.1.6
  ntp: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  jaguar_orm_gen: any
  build_runner: ^1.7.4

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/hasbah_icon.png
    - assets/images/icon.png
    - assets/images/pwani_icon.png
    - assets/images/united_icon.png
    - assets/images/capwell_icon.png
    - assets/images/ki_icon.png
    - assets/images/highlands_icon.png
    - assets/images/solutech.png
    - assets/images/avatar.jpg
    - assets/images/qr-code.png
    - assets/images/pending.png
    - assets/images/barcode-grey.png
    - assets/images/barcode.png
    - assets/images/noimage.jpg
    - assets/images/marker.png
    - assets/images/geofencing.PNG
    - assets/images/permissions.png
    - assets/images/shopping-bag.png
    - assets/images/shopping-cart.png
    - assets/images/destination.png
    - assets/images/feedback.png
    - assets/images/bar-chart.png
    - assets/images/boxes.png
    - assets/images/camera.png
    - assets/images/inventory.png
    - assets/images/shopping-list.png
    - assets/images/conversation.png
    - assets/images/competition.png
    - assets/images/location.png
    - assets/images/location-off.png
    - assets/images/shelf.png
    - assets/images/delivery-truck.png
    - assets/images/damage.png
    - assets/images/pay.png
    - assets/images/crate.png
    - assets/images/expiry.png
    - assets/images/shelf-display.png
    - assets/images/cash-collection.png
    - assets/images/bowip_icon.jpg
    - assets/images/map-marker.png
    - assets/images/sell.png
    - assets/images/customers.png
    - assets/images/qualitative_research.png
    - assets/images/order.png
    - assets/images/skip.png
    - assets/i18n/en.json
    - assets/i18n/fr.json
    - assets/images/pos.png
    - assets/images/ketepa_icon.png
    - assets/images/palmhouse_icon.png
    - assets/images/banking.png
    - assets/images/mzuri_icon.png
    - assets/images/mzawadi.png
    - assets/images/pezesha.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
